var _ = {
  ENV: "ENV",
  USER_INFO:"USER_INFO",
  LOGIN_INFO:"LOGIN_INFO",
  USER_AUTHORIZE:"USER_AUTHORIZE",
  SESSION_ID:"SESSION_ID",
  CUSTID:"CUSTID",
  CUST_ID:"CUST_ID",
  USER_ID:"USER_ID",
  OPERSTAFFSEQ:"OPERSTAFFSEQ",
  EWCORPID:"EWCORPID",
  AUTH_DATA:"AUTHDATA"
}


module.exports = {
  STORAGE: _
};